Add WinUI 3 build validation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,8 +17,8 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
+  # This workflow contains a single job called "Build WinUI 2"
+  Build WinUI 2:
     # The type of runner that the job will run on
     runs-on: windows-latest
 
@@ -73,6 +73,87 @@ jobs:
         if: ${{github.ref == 'refs/heads/main'}}
         run: dotnet nuget push "**/*.nupkg" --api-key dummy --source LabsFeed --skip-duplicate
 
+
+      # Run tests
+      - name: Setup VSTest Path
+        uses: darenm/Setup-VSTest@v1
+
+      - name: Run SourceGenerators tests
+        run: vstest.console.exe ./Common/CommunityToolkit.Labs.Core.SourceGenerators.Tests/CommunityToolkit.Labs.Core.SourceGenerators.Tests/bin/Release/net6.0/CommunityToolkit.Labs.Core.SourceGenerators.Tests.dll /logger:"trx;LogFileName=SourceGenerators.trx"
+
+      - name: Run experiment tests against UWP
+        run:  vstest.console.exe ./Tests/**/CommunityToolkit.Labs.UnitTests.UWP.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=UWP.trx"
+
+      - name: Run experiment tests against WinAppSDK
+        run:  vstest.console.exe ./Tests/**/CommunityToolkit.Labs.UnitTests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=WinAppSdk.trx"
+
+      - name: Create test reports
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test results
+          path: './TestResults/*.trx'
+          reporter: dotnet-trx
+
+  # This workflow contains a single job called "Build WinUI 3"
+  Build WinUI 3:
+    # The type of runner that the job will run on
+    runs-on: windows-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+      # Needed until XAML Styler updates to .NET 6
+      - name: Install .NET Core 3.1 SDK
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '3.1.x'
+
+      - name: Install .NET 6 SDK
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '6.0.201'
+
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      # Restore Tools from Manifest list in the Repository
+      - name: Restore dotnet tools
+        run: dotnet tool restore
+
+      - name: Check XAML Styling
+        run: ./ApplyXamlStyling.ps1 -Passive
+
+      - name: Run Uno Check to Install Dependencies
+        run: dotnet tool run uno-check --ci --fix --non-interactive --skip wsl --skip androidemulator #--verbose
+
+      - name: Add msbuild to PATH
+        uses: microsoft/setup-msbuild@v1.0.3
+
+      - name: Enable all TargetFrameworks
+        working-directory: ./common/Scripts/
+        run: ./UseTargetFrameworks.ps1 all
+
+      - name: Enable WinUI 3
+        working-directory: ./common/Scripts/
+        run: ./UseUnoWinUI.ps1 3
+
+      - name: MSBuild
+       # working-directory: ./
+        run: msbuild.exe Toolkit.Labs.All.sln /restore -p:Configuration=Release
+
+      # Build All Packages - TODO: Detect experiments
+      - name: pack CanvasLayout
+        working-directory: ./labs/CanvasLayout/src
+        run: msbuild -t:pack /p:Configuration=Release /p:DebugType=Portable
+
+      # Push Packages to our DevOps Artifacts Feed
+      - name: Add source
+        run: dotnet nuget add source "https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json" --name LabsFeed --username dummy --password ${{ secrets.DEVOPS_PACKAGE_PUSH_TOKEN }}
+
+      - name: Push packages
+        if: ${{github.ref == 'refs/heads/main'}}
+        run: dotnet nuget push "**/*.nupkg" --api-key dummy --source LabsFeed --skip-duplicate
 
       # Run tests
       - name: Setup VSTest Path
