Revert "Merge branch 'main' into niels9001/settingscontrols-uifixes"
This reverts commit f2f3bc24ade2f9d967f52c5f0ce82a6bb297f2be, reversing
changes made to 25655e0d40fafc9d5db864a451045b50ed1f9941.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,11 +15,6 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-env:
-  DOTNET_VERSION: ${{ '6.0.x' }}
-  ENABLE_DIAGNOSTICS: false
-  #COREHOST_TRACE: 1
-  COREHOST_TRACEFILE: corehosttrace.log
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -29,10 +24,10 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - name: Install .NET SDK v${{ env.DOTNET_VERSION }}
+      - name: Install .NET 6 SDK
         uses: actions/setup-dotnet@v3
         with:
-          dotnet-version: ${{ env.DOTNET_VERSION }}
+          dotnet-version: '6.0.x'
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout Repository
@@ -63,14 +58,10 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - name: Install .NET SDK v${{ env.DOTNET_VERSION }}
+      - name: Install .NET 6 SDK
         uses: actions/setup-dotnet@v3
         with:
-          dotnet-version: ${{ env.DOTNET_VERSION }}
-
-      - name: .NET Info (if diagnostics)
-        if: ${{ env.ENABLE_DIAGNOSTICS == 'true' }}
-        run: dotnet --info
+          dotnet-version: '6.0.x'
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout Repository
@@ -84,18 +75,18 @@ jobs:
         run: dotnet tool run uno-check --ci --fix --non-interactive --skip wsl --skip androidemulator --verbose
 
       - name: Add msbuild to PATH
-        uses: microsoft/setup-msbuild@v1.3.1
+        uses: microsoft/setup-msbuild@v1.0.3
 
       - name: Enable ${{ env.TARGET_PLATFORMS }} TargetFrameworks
-        working-directory: ./common/MultiTarget/
+        working-directory: ./common/Scripts/
         run: powershell -version 5.1 -command "./UseTargetFrameworks.ps1 ${{ env.TARGET_PLATFORMS }}" -ErrorAction Stop
 
       - name: Generate solution w/ ${{ env.TEST_PLATFORM }} Tests
         working-directory: ./
-        run: powershell -version 5.1 -command "./common/GenerateAllSolution.ps1 -IncludeHeads ${{ env.TEST_PLATFORM }}${{ env.ENABLE_DIAGNOSTICS == 'true' && ' -UseDiagnostics' || '' }}" -ErrorAction Stop
+        run: powershell -version 5.1 -command "./common/GenerateAllSolution.ps1 -IncludeHeads ${{ env.TEST_PLATFORM }}" -ErrorAction Stop
 
       - name: Enable Uno.WinUI (in WinUI3 matrix only)
-        working-directory: ./common/MultiTarget/
+        working-directory: ./common/Scripts/
         run: powershell -version 5.1 -command "./UseUnoWinUI.ps1 3" -ErrorAction Stop
         if: ${{ matrix.platform == 'WinUI3' }}
 
@@ -127,82 +118,59 @@ jobs:
 
       - name: Run SourceGenerators tests
         id: test-generator
-        run: vstest.console.exe ./common/CommunityToolkit.Tooling.SampleGen.Tests/bin/Release/net6.0/CommunityToolkit.Tooling.SampleGen.Tests.dll /logger:"trx;LogFileName=SourceGenerators.trx"
+        run: vstest.console.exe ./common/CommunityToolkit.Labs.Core.SourceGenerators.Tests/CommunityToolkit.Labs.Core.SourceGenerators.Tests/bin/Release/net6.0/CommunityToolkit.Labs.Core.SourceGenerators.Tests.dll /logger:"trx;LogFileName=SourceGenerators.trx"
 
       - name: Run experiment tests against ${{ env.TEST_PLATFORM }}
         id: test-platform
-        run:  vstest.console.exe ./common/**/CommunityToolkit.Tests.${{ env.TEST_PLATFORM }}.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=${{ env.TEST_PLATFORM }}.trx"
+        run:  vstest.console.exe ./tests/**/CommunityToolkit.Labs.Tests.${{ env.TEST_PLATFORM }}.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=${{ env.TEST_PLATFORM }}.trx"
 
       - name: Create test reports
         run: |
           testspace '[${{ matrix.platform }}]./TestResults/*.trx'
         if: ${{ always() && (steps.test-generator.conclusion == 'success' || steps.test-platform.conclusion == 'success') }}
 
-      - name: Artifact - Diagnostic Logs
-        uses: actions/upload-artifact@v3
-        if: ${{ (env.ENABLE_DIAGNOSTICS == 'true' || env.COREHOST_TRACE != '') && always() }}
-        with:
-          name: build-logs
-          path: ./**/*.*log
+      #- name: Artifact - Slngen Logs
+      #  uses: actions/upload-artifact@v3
+      #  if: success() || failure()
+      #  with:
+      #    name: slngen-logs
+      #    path: ./**/slngen.*log
 
   # Test job to build a single experiment to ensure our changes work for both our main types of solutions at the moment
   new-experiment:
-    # TODO: We should only run this if something in the common or template folder changed...
+    needs: [Xaml-Style-Check]
     runs-on: windows-latest
-    env:
-      PROJECT_DIRECTORY: template/ProjectTemplate
-      TEST_PROJECT_NAME: CiTestExp
-      TEST_PROJECT_DIRECTORY: labs/CiTestExp
 
     steps:
-      - name: Install .NET SDK v${{ env.DOTNET_VERSION }}
+      - name: Install .NET 6 SDK
         uses: actions/setup-dotnet@v3
         with:
-          dotnet-version: ${{ env.DOTNET_VERSION }}
-
-      - name: .NET Info (if diagnostics)
-        if: ${{ env.ENABLE_DIAGNOSTICS == 'true' }}
-        run: dotnet --info
-
-      - name: Enable git long paths
-        run: git config --system core.longpaths true
+          dotnet-version: '6.0.x'
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout Repository
         uses: actions/checkout@v3
 
       - name: Add msbuild to PATH
-        uses: microsoft/setup-msbuild@v1.3.1
-
-      - name: Add project heads to ProjectTemplate
-        working-directory: ./${{ env.PROJECT_DIRECTORY }}
-        run: ${{ github.workspace }}/common/ProjectHeads/GenerateSingleSampleHeads.ps1 -componentPath ${{ github.workspace }}/${{ env.PROJECT_DIRECTORY }}${{ env.ENABLE_DIAGNOSTICS == 'true' && ' -UseDiagnostics' || '' }}
+        uses: microsoft/setup-msbuild@v1.0.3
 
       # Build and use template for creating new experiments
       - name: Build ProjectTemplate
-        working-directory: ./${{ env.PROJECT_DIRECTORY }}
+        working-directory: ./template/lab
         run: msbuild.exe ProjectTemplate.sln /restore /nowarn:MSB4011 -p:Configuration=Debug
-
-      - name: Clean environment
-        working-directory: ./
-        run: git clean -xdf
 
       # Create a new experiment from the template and test using that
       - name: Install template
-        working-directory: ${{ env.PROJECT_DIRECTORY }}
+        working-directory: ./template/lab
         run: dotnet new --install ./
 
       - name: Create new experiment
         working-directory: ./labs
-        run: dotnet new labexp -n ${{ env.TEST_PROJECT_NAME }}
-
-      - name: Add project heads to ${{ env.TEST_PROJECT_NAME }}
-        working-directory: ./${{ env.TEST_PROJECT_DIRECTORY }}
-        run: ${{ github.workspace }}/common/ProjectHeads/GenerateSingleSampleHeads.ps1 -componentPath ${{ github.workspace }}/${{ env.TEST_PROJECT_DIRECTORY }}${{ env.ENABLE_DIAGNOSTICS == 'true' && ' -UseDiagnostics' || '' }}
+        run: dotnet new labexp -n CiTestExp
 
       - name: MSBuild
-        working-directory: ./${{ env.TEST_PROJECT_DIRECTORY }}
-        run: msbuild.exe ${{ env.TEST_PROJECT_NAME }}.sln /restore /nowarn:MSB4011 -p:Configuration=Release
+        working-directory: ./labs/CiTestExp
+        run: msbuild.exe CiTestExp.sln /restore /nowarn:MSB4011 -p:Configuration=Release
 
       # Run tests
       - name: Setup VSTest Path
@@ -215,36 +183,26 @@ jobs:
 
       - name: Run tests in the generated experiment against UWP
         id: test-uwp
-        run:  vstest.console.exe ./labs/${{ env.TEST_PROJECT_NAME }}/**/${{ env.TEST_PROJECT_NAME }}.Tests.UWP.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=${{ env.TEST_PROJECT_NAME }}UWP.trx"
+        run:  vstest.console.exe ./labs/CiTestExp/**/CiTestExp.Tests.UWP.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=CiTestExpUWP.trx"
 
       - name: Run tests in the generated experiment against WinAppSDK
         id: test-winappsdk
-        run:  vstest.console.exe ./labs/${{ env.TEST_PROJECT_NAME }}/**/${{ env.TEST_PROJECT_NAME }}.Tests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=${{ env.TEST_PROJECT_NAME }}WinAppSdk.trx"
+        run:  vstest.console.exe ./labs/CiTestExp/**/CiTestExp.Tests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=CiTestExpWinAppSdk.trx"
 
       - name: Create test reports
         run: |
           testspace '[New Experiment]./TestResults/*.trx'
         if: ${{ always() && (steps.test-uwp.conclusion == 'success' || steps.test-winappsdk.conclusion == 'success') }}
 
-      - name: Artifact - Diagnostic Logs
-        uses: actions/upload-artifact@v3
-        if: ${{ (env.ENABLE_DIAGNOSTICS == 'true' || env.COREHOST_TRACE != '') && always() }}
-        with:
-          name: new-experiment-logs
-          path: ./**/*.*log
-
   wasm-linux:
+    needs: [Xaml-Style-Check]
     runs-on: ubuntu-latest
 
     steps:
-      - name: Install .NET SDK v${{ env.DOTNET_VERSION }}
+      - name: Install .NET 6 SDK
         uses: actions/setup-dotnet@v3
         with:
-          dotnet-version: ${{ env.DOTNET_VERSION }}
-
-      - name: .NET Info (if diagnostics)
-        if: ${{ env.ENABLE_DIAGNOSTICS == 'true' }}
-        run: dotnet --info
+          dotnet-version: '6.0.x'
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout Repository
@@ -257,22 +215,22 @@ jobs:
       - name: Generate solution
         shell: pwsh
         working-directory: ./
-        run: ./common/GenerateAllSolution.ps1${{ env.ENABLE_DIAGNOSTICS == 'true' && ' -UseDiagnostics' || '' }}
+        run: ./common/GenerateAllSolution.ps1
 
       - name: Install ninja for WASM native dependencies
         run: sudo apt-get install ninja-build
 
       # Issue with Comment Links currently, see: https://github.com/mrlacey/CommentLinks/issues/38
-      # See launch.json configuration file for analogous command we're emulating here to build LINK: ../../.vscode/launch.json:CommunityToolkit.App.Wasm.csproj
+      # See launch.json configuration file for analogous command we're emulating here to build LINK: ../../.vscode/launch.json:CommunityToolkit.Labs.Wasm.csproj
       - name: dotnet build
-        working-directory: ./common/ProjectHeads/AllComponents/Wasm/
+        working-directory: ./platforms/CommunityToolkit.Labs.Wasm/
         run: dotnet build /r /bl /p:UnoSourceGeneratorUseGenerationHost=true /p:UnoSourceGeneratorUseGenerationController=false
   
       # TODO: Do we want to run tests here? Can we do that on linux easily?
 
-      - name: Artifact - Diagnostic Logs
-        uses: actions/upload-artifact@v3
-        if: ${{ (env.ENABLE_DIAGNOSTICS == 'true' || env.COREHOST_TRACE != '') && always() }}
-        with:
-          name: linux-logs
-          path: ./**/*.*log
+      #- name: Artifact - Slngen Logs
+      #  uses: actions/upload-artifact@v3
+      #  if: success() || failure()
+      #  with:
+      #    name: slngen-logs
+      #    path: ./**/slngen.*log
