Turn off diagnostics for Solution Generation, leave hint at uploading logs in the build script.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -83,7 +83,7 @@ jobs:
 
       - name: Generate solution w/ ${{ env.TEST_PLATFORM }} Tests
         working-directory: ./
-        run: powershell -version 5.1 -command "./common/GenerateAllSolution.ps1 -IncludeHeads ${{ env.TEST_PLATFORM }} -UseDiagnostics" -ErrorAction Stop
+        run: powershell -version 5.1 -command "./common/GenerateAllSolution.ps1 -IncludeHeads ${{ env.TEST_PLATFORM }}" -ErrorAction Stop
 
       - name: Enable Uno.WinUI (in WinUI3 matrix only)
         working-directory: ./common/Scripts/
@@ -129,12 +129,12 @@ jobs:
           testspace '[${{ matrix.platform }}]./TestResults/*.trx'
         if: ${{ always() && (steps.test-generator.conclusion == 'success' || steps.test-platform.conclusion == 'success') }}
 
-      - name: Artifact - Slngen Logs
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: slngen-logs
-          path: ./**/slngen.*log
+      #- name: Artifact - Slngen Logs
+      #  uses: actions/upload-artifact@v3
+      #  if: success() || failure()
+      #  with:
+      #    name: slngen-logs
+      #    path: ./**/slngen.*log
 
   # Test job to build a single experiment to ensure our changes work for both our main types of solutions at the moment
   new-experiment:
@@ -215,7 +215,7 @@ jobs:
       - name: Generate solution
         shell: pwsh
         working-directory: ./
-        run: ./common/GenerateAllSolution.ps1 -UseDiagnostics
+        run: ./common/GenerateAllSolution.ps1
 
       - name: Install ninja for WASM native dependencies
         run: sudo apt-get install ninja-build
@@ -228,9 +228,9 @@ jobs:
   
       # TODO: Do we want to run tests here? Can we do that on linux easily?
 
-      - name: Artifact - Slngen Logs
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: slngen-logs
-          path: ./**/slngen.*log
+      #- name: Artifact - Slngen Logs
+      #  uses: actions/upload-artifact@v3
+      #  if: success() || failure()
+      #  with:
+      #    name: slngen-logs
+      #    path: ./**/slngen.*log
