test the template as a separate CI job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,14 +52,6 @@ jobs:
         working-directory: ./template/lab
         run: msbuild.exe ProjectTemplate.sln /restore -p:Configuration=Debug
 
-      - name: Install template
-        working-directory: ./template/lab
-        run: dotnet new --install ./
-
-      - name: Create new experiment
-        working-directory: ./labs
-        run: dotnet new labexp -n CiTestExp2
-
       - name: Generate solution
         run: ./GenerateAllSolution.ps1
 
@@ -90,8 +82,8 @@ jobs:
       - name: Run experiment tests against UWP
         run:  vstest.console.exe ./tests/**/CommunityToolkit.Labs.UnitTests.UWP.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=UWP.trx"
 
-      - name: Run tests in the ProjectTemplate against UWP
-        run:  vstest.console.exe ./template/lab/**/ProjectTemplate.UnitTests.UWP.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=ProjectTemplateUWP.trx"
+      - name: Run experiment tests against WinAppSDK
+        run:  vstest.console.exe ./tests/**/CommunityToolkit.Labs.UnitTests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=WinAppSdk.trx"
 
       - name: Create test reports
         uses: dorny/test-reporter@v1
@@ -136,14 +128,6 @@ jobs:
         working-directory: ./template/lab
         run: msbuild.exe ProjectTemplate.sln /restore -p:Configuration=Debug
 
-      - name: Install template
-        working-directory: ./template/lab
-        run: dotnet new --install ./
-
-      - name: Create new experiment
-        working-directory: ./labs
-        run: dotnet new labexp -n CiTestExp3
-
       - name: Generate solution
         run: ./GenerateAllSolution.ps1
 
@@ -175,11 +159,11 @@ jobs:
       - name: Run SourceGenerators tests
         run: vstest.console.exe ./common/CommunityToolkit.Labs.Core.SourceGenerators.Tests/CommunityToolkit.Labs.Core.SourceGenerators.Tests/bin/Release/net6.0/CommunityToolkit.Labs.Core.SourceGenerators.Tests.dll /logger:"trx;LogFileName=SourceGenerators.trx"
 
+      - name: Run experiment tests against UWP
+        run:  vstest.console.exe ./tests/**/CommunityToolkit.Labs.UnitTests.UWP.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=UWP.trx"
+
       - name: Run experiment tests against WinAppSDK
         run:  vstest.console.exe ./tests/**/CommunityToolkit.Labs.UnitTests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=WinAppSdk.trx"
-
-      - name: Run tests in the ProjectTemplate against WinAppSDK
-        run:  vstest.console.exe ./template/lab/**/ProjectTemplate.UnitTests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=ProjectTemplateWinAppSdk.trx"
 
       - name: Create test reports
         uses: dorny/test-reporter@v1
@@ -188,7 +172,7 @@ jobs:
           name: Test results
           path: './TestResults/*.trx'
           reporter: dotnet-trx
-  
+
   # This workflow contains a single job called "Xaml-Style-Check"
   Xaml-Style-Check:
     # The type of runner that the job will run on
@@ -230,6 +214,32 @@ jobs:
       - name: Add msbuild to PATH
         uses: microsoft/setup-msbuild@v1.0.3
 
+      - name: Install template
+        working-directory: ./template/lab
+        run: dotnet new --install ./
+
+      - name: Create new experiment
+        working-directory: ./labs
+        run: dotnet new labexp -n CiTestExp
+
       - name: MSBuild
-        working-directory: ./labs/CanvasLayout
-        run: msbuild.exe CanvasLayout.sln /restore -p:Configuration=Release
+        working-directory: ./labs/CiTestExp
+        run: msbuild.exe CiTestExp.sln /restore -p:Configuration=Release
+
+      # Run tests
+      - name: Setup VSTest Path
+        uses: darenm/Setup-VSTest@v1
+
+      - name: Run tests in the generated experiment against UWP
+        run:  vstest.console.exe ./labs/CiTestExp/**/CiTestExp.UnitTests.UWP.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=CiTestExpUWP.trx"
+
+      - name: Run tests in the generated experiment against WinAppSDK
+        run:  vstest.console.exe ./labs/CiTestExp/**/CiTestExp.UnitTests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=CiTestExpWinAppSdk.trx"
+
+      - name: Create test reports
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test results
+          path: './TestResults/*.trx'
+          reporter: dotnet-trx
